rootProject.name = "android-interview-practice"

pluginManagement {
    repositories {
        google()
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}

// One module per topic. Each is self-contained: open the root once in Android
// Studio (or IntelliJ) and run any topic on its own.
include(":nothing-any")
include(":null-safety")
include(":coroutines-basics")
include(":extensions")
include(":generics-variance")
include(":kotlin-classes")
include(":lambdas-inline")
include(":scope-functions")
include(":collections")
include(":concurrent-collections")
include(":channels")
include(":concurrenthashmap")
include(":coroutines-structured")
include(":delegation")
include(":mvi")
include(":properties")
include(":stateflow-sharedflow")
include(":tokens-idempotency")
include(":clean-arch")
include(":flow-operators")
include(":interceptors")
include(":jmm")
include(":mvvm-udf")
include(":repository")
include(":serialization")
include(":testing-flow")
include(":threading")
include(":viewmodel-state")
include(":deep-link-routing")
include(":manual-di")
include(":offline-first")
include(":permission-state")
include(":resource-qualifiers")
include(":saved-state")
include(":test-doubles")
include(":work-queue")

// Exercises for the remaining topics.
include(":flow-basics")
include(":activity-lifecycle")
include(":fragment-lifecycle")
include(":broadcast-router")
include(":manifest-merge")
include(":diff-util")
include(":lifecycle-collect")
include(":paging-source")
include(":hilt-bindings")
include(":scope-hierarchy")
include(":url-resolution")
include(":image-cache")
include(":dao-migrations")
include(":preferences-store")
include(":semantics-tree")
include(":task-graph")
include(":variant-matrix")
include(":reachability")
include(":module-graph")
include(":anr-detector")
include(":startup-order")
include(":frame-budget")
include(":doze-scheduler")
include(":cert-pinning")
include(":secure-store")
include(":input-validation")
include(":expect-actual")
include(":sensor-fusion")
include(":compose-state")
include(":compose-mental")
include(":compose-effects")
include(":compose-layout")
include(":compose-animation")
include(":material3-theming")
include(":compose-navigation")
include(":compose-perf")
include(":recyclerview")
include(":room-db")
include(":datastore-prefs")
include(":paging-list")
include(":viewmodel-real")
include(":lifecycle-real")
include(":coil-images")
include(":retrofit-api")
include(":stability-inference")
